version: '3.3'
services:
  bot:
    build: 
     context: .
     dockerfile: Dockerfile
    container_name: uaimo_obuch_bot
    command: python run_bot.py
    ports:
      - 80:80
    volumes:
      - /opt/uaimo_obuch_bot:/uaimo_obuch_bot
